import = [".config/alacritty/plugins/dracula/dracula.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.bold]
family = "0xProto Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font"
style = "Light Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 9000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0

